---
title: "Shrinkage methods"
subtitle: "for regression"
output:
  xaringan::moon_reader:
    css: [default, metropolis-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# motivation

#### Genome Wide Association Studies (GWAS)
 - 1,000s of covariates, 100s of data points
 - most of them unrelated

---
# motivation

#### Something else
 - i dunno

---

# the idea

---
# ridge regression
```{r echo=FALSE}
library(shiny)
library(glmnet)
library(widgetframe)

set.seed(1)

powerify <- function (x, times = length(x)) {
  powers <- seq_len(times - 1)
  sapply(powers,
         function(y, x) x ^ y,
         x)
}

# generate bins based on input$bins from ui.R
n <- 30
x <- powerify(runif(n))
y <- rnorm(n)

lambda_max <- 1
lambda_step <- 0.00005
lambdas <- seq(lambda_max, lambda_step, by = -lambda_step)
m <- glmnet::glmnet(x, y, alpha = 0, lambda = lambdas)

# predictions
x_seq <- powerify(seq(0, 1, length.out = 1000), n)
preds <- predict(m, x_seq)

# keep only those glmnet models that converged
idx <- as.numeric(gsub("^s", "", colnames(preds)))
lambdas <- lambdas[idx + 1]

# add the 0-case
# 0-case
m2 <- lm(y ~ ., data = data.frame(x))
pred0 <- predict(m2, newdata = data.frame(x_seq))

preds <- cbind(preds, pred0)
lambdas <- c(lambdas, 0)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("ridge regression"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         sliderInput("penalty",
                     "ridge penalty:",
                     min = 0,
                     max = lambda_max,
                     value = 0,
                     step = lambda_step)
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         plotOutput("line_plot")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
   output$line_plot <- renderPlot({
      
      i = which.min(abs(lambdas - input$penalty))
      
      # draw the histogram with the specified number of bins
      plot.new()
      plot.window(x = range(x[, 2]),
                  y = range(y))
      
      points(y ~ x[, 2],
           pch = 16,
           col = 'darkgray')
      axis(1)
      axis(2, las = 1)
      title(xlab = "x")
      mtext("y", 2, las = 1, line = 3)
      
      lines(preds[, i] ~ x_seq[, 2],
           lwd = 3,
           col = 'hotpink')
   })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

---
# the lasso

---
class: inverse, center, middle

# Bayesian equivalence

---

# Bayesian ridge regression

## [$$\beta_i \sim N(0, 1)$$]()
## $$\epsilon_i \sim N(0, \sigma^2)$$
## $$y = \mathbf{X} \beta + \epsilon$$
---
# Bayesian lasso

[$$\beta_i \sim Laplace(0, 1)$$]()
$$\epsilon_i \sim N(0, \sigma^2)$$
$$y = \mathbf{X} \beta + \epsilon$$

---
class: center, middle

`r icon::fa("github", 5)`
### [`github.com/goldingn/shrinkage_lecture`](https://github.com/goldingn/shrinkage_lecture)

